name: spotify_analytics
version: "1.0.0"
config-version: 2

profile: spotify_analytics

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  spotify_analytics:
    staging:
      +materialized: view
      +schema: spotify_staging
    intermediate:
      +materialized: view
      +schema: spotify_intermediate
    marts:
      +materialized: table
      +schema: spotify_marts
